development:
  adapter: postgresql
  database: newzmaps_development
  pool: 5
  timeout: 5000
  host: localhost
  password: password


test:
  adapter: postgresql
  database: newzmaps_test
  pool: 5
  timeout: 5000
  host: localhost
  password: password


production:
  adapter: postgresql
  database: newzmaps_production
  url: <%= ENV["DATABASE_URL"] %>
  pool: 5
  timeout: 5000
